# Generated by Django 3.0.3 on 2020-08-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggingapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spectrometer_measure',
            new_name='Spectrometermeasure',
        ),
    ]
